import "./globals.css";
import type { Metadata } from "next";
import { Work_Sans, Mulish } from "next/font/google";

const WorkSansFont = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal"],
  display: "swap",
});

const MulishFont = Mulish({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  style: ["normal"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${WorkSansFont.className} ${MulishFont.className}`}>
        {children}
      </body>
    </html>
  );
}
